networks:
  work:

services:
  nginx:
    image: nginx:1.21.0-alpine
    container_name: nginx-work
    environment:
      TZ: Europe/Kiev
    ports:
      - "80:80" #Если ругается что какой-то порт занят попробуйте сменить первую 80 на что-то другое, допустим на - "83:80"
      - "443:443"
    volumes:
      - ./src:/var/www/src
      - ./nginx/logs:/var/log/nginx #логи будут "синхронизироватся" в эту папку (nginx/logs)
      - ./nginx/conf/default.conf:/etc/nginx/conf.d/default.conf #пробрасываем конфиг в нужную папку
    depends_on:
      - php
      - node
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - work

  php:
    build:
      context: ./php-cli
      dockerfile: Dockerfile.fpm
    container_name: php-work
    environment:
      TZ: Europe/Kiev
    volumes:
      - ./src:/var/www/src
      - ./php-cli/php.ini:/usr/local/etc/php/conf.d/40-custom.ini
    networks:
      - work

  node:
    image: node:latest
    container_name: node-work
    environment:
      TZ: Europe/Kiev
    ports:
      - "5174:5173"
    volumes:
      - ./frontend:/var/www/
#      - /var/www/frontend/node_modules
    working_dir: /var/www/
    restart: unless-stopped
    entrypoint: ["npm", "run", "dev"]
    networks:
      - work


  mysql:
    image: mysql:latest
    container_name: mysql-work
    restart: unless-stopped
    tty: true
    ports:
      - "3307:3306"
    volumes:
        - ./mysql:/var/lib/mysql
    environment:
      TZ: Europe/Kiev
      MYSQL_DATABASE: palmo
      MYSQL_USER: palmo
      MYSQL_PASSWORD: palmo
      MYSQL_ROOT_PASSWORD: palmo
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - work

  artisan:
    build:
      context: ./php-cli
      dockerfile: Dockerfile
    container_name: artisan-work
    environment:
      TZ: Europe/Kiev
    volumes:
      - ./src:/var/www/src
    depends_on:
      - mysql
    working_dir: /var/www/src
    entrypoint: ["php", "/var/www/src/artisan"]
    networks:
      - work